### PR TITLE
fix: file name

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**

### CODE REVIEW

**Comment by JaydenTD500** [comment]
It’s suppose to be like that

**Comment by JaydenTD500** [comment]
@WilliamDavidHarrison Please Close this pull request

**Comment by cph101** [comment]
No, @WilliamDavidHarrison is right.

**Review by cph101 — COMMENTED** [review]
This is good

**Comment by cph101** [comment]
@WilliamDavidHarrison please reopen so that I can merge it.

**Comment by CrazyH2** [comment]
> This is good

It is not right

**Comment by CrazyH2** [comment]
It is not meant to have .txt

**Comment by WilliamDavidHarrison** [comment]
> It is not meant to have .txt

The file doesn't have .txt in the file name though.

**Comment by cph101** [comment]
> > This is good
> 
> It is not right

I MEAN THE PULL REQUEST IS GOOD

**Pull request closed without merging**
